(function attachHelixCapitalAppeals(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.HelixCapitalAppeals = api;
}(typeof globalThis !== "undefined" ? globalThis : this, function createHelixCapitalAppeals() {
  "use strict";

  const VERSION = 1;
  const HOUR = 3600;
  const DAY = 24 * HOUR;
  const AUTOMATIC_DECISION_DELAY = 2 * DAY;
  const DIRECT_APPEAL_DEADLINE = 10 * DAY;
  const DIRECT_DECISION_DELAY = 3 * DAY;
  const MINIMUM_POST_ADVERSE_DELAY = 3 * DAY;
  const CLAIMS = Object.freeze([
    { id: "insufficientProof", label: "Insufficient Proof of a Required Element", remedy: "convictionReversal" },
    { id: "improperlyAdmittedEvidence", label: "Improperly Admitted Evidence", remedy: "convictionReversal" },
    { id: "brokenEvidenceIntegrity", label: "Broken Evidence Custody or Integrity", remedy: "convictionReversal" },
    { id: "proceduralError", label: "Material Procedural Error", remedy: "convictionReversal" },
    { id: "unsupportedCapitalEligibility", label: "Unsupported Capital Eligibility or Aggravation", remedy: "sentenceReversal" },
    { id: "ineffectiveRepresentation", label: "Ineffective Representation", remedy: "convictionReversal" }
  ]);
  const GIVEN = Object.freeze(["Asha", "Cal", "Dane", "Ivo", "Jori", "Mara", "Miko", "Nia", "Oren", "Rian", "Sera", "Tamsin", "Vela"]);
  const FAMILY = Object.freeze(["Aster", "Dunn", "Kade", "Keene", "Morrow", "Pike", "Rusk", "Sloane", "Thorne", "Vale", "Voss", "Ward"]);

  function finite(value, fallback = 0) { const number = Number(value); return Number.isFinite(number) ? number : fallback; }
  function round(value) { return Math.round(finite(value) * 100) / 100; }
  function clamp(value, minimum, maximum) { return Math.max(minimum, Math.min(maximum, finite(value))); }
  function cleanId(value) { return String(value || "").trim().replace(/[^a-zA-Z0-9:_-]/g, ""); }
  function clone(value) { return value == null ? value : JSON.parse(JSON.stringify(value)); }
  function unique(values) { return [...new Set((Array.isArray(values) ? values : []).map(String).filter(Boolean))]; }
  function hash(seed) { let value = 2166136261; for (const character of String(seed || "appeal")) { value ^= character.charCodeAt(0); value = Math.imul(value, 16777619); } return value >>> 0; }
  function actorName(seed, index) { return `${GIVEN[hash(`${seed}:${index}:given`) % GIVEN.length]} ${FAMILY[hash(`${seed}:${index}:family`) % FAMILY.length]}`; }
  function textOf(entry) { return [entry?.label, ...(entry?.traits || [])].join(" ").toLowerCase(); }

  function normalizeClaim(value, index = 0) {
    const def = CLAIMS.find((entry) => entry.id === value?.id) || CLAIMS[index] || CLAIMS[0];
    return { id: def.id, label: def.label, remedy: def.remedy, supported: Boolean(value?.supported), baseScore: clamp(value?.baseScore, 0, 100), reasons: unique(value?.reasons), recordRefs: unique(value?.recordRefs) };
  }
  function normalizePanelMember(value, index = 0) { return { id: cleanId(value?.id) || `capital-appellate-judge-${index + 1}`, name: String(value?.name || `Appellate Judge ${index + 1}`).trim(), role: index === 0 ? "presidingAppellateJudge" : "appellateJudge", proceduralStrictness: clamp(value?.proceduralStrictness ?? 60, 20, 95) }; }
  function normalizeOutcome(value) { if (!value || typeof value !== "object") return null; return { kind: ["affirmed", "sentenceReversal", "convictionReversal", "finalReversalRelease"].includes(value.kind) ? value.kind : "affirmed", decidedAt: Math.max(0, finite(value.decidedAt)), claimId: cleanId(value.claimId), summary: String(value.summary || "The panel entered a written capital decision.").trim(), reasons: unique(value.reasons), successorKind: cleanId(value.successorKind), excludedSupportIds: unique(value.excludedSupportIds), final: value.final !== false }; }
  function normalizeFiling(value) { const source = value && typeof value === "object" ? value : {}; return { status: ["available", "filed", "affirmed", "relief", "deadlineMissed"].includes(source.status) ? source.status : "available", filedAt: source.filedAt == null ? null : Math.max(0, finite(source.filedAt)), decisionAt: source.decisionAt == null ? null : Math.max(0, finite(source.decisionAt)), primaryClaimId: cleanId(source.primaryClaimId), secondaryClaimId: cleanId(source.secondaryClaimId), frozen: source.frozen && typeof source.frozen === "object" ? clone(source.frozen) : null, outcome: normalizeOutcome(source.outcome) }; }
  function normalizeDecision(value) { return { required: Boolean(value?.required), kind: cleanId(value?.kind), reason: String(value?.reason || "").trim(), raisedAt: value?.raisedAt == null ? null : Math.max(0, finite(value.raisedAt)) }; }
  function normalizeHistory(value) { return (Array.isArray(value) ? value : []).map((entry) => ({ at: Math.max(0, finite(entry?.at)), action: cleanId(entry?.action) || "updated", summary: String(entry?.summary || "Capital appeal updated.").trim() })).sort((a, b) => a.at - b.at); }

  function claimInputs(caseRecord = {}, proceeding = {}) {
    const guilty = (caseRecord.charges || []).filter((charge) => charge.verdict === "guilty");
    const admitted = guilty.flatMap((charge) => (charge.support || []).filter((support) => support.admissibility !== "excluded"));
    const elements = guilty.flatMap((charge) => charge.elements || []); const minimumMargin = elements.length ? Math.min(...elements.map((element) => finite(element.margin))) : 0;
    const weakElements = elements.filter((element) => finite(element.margin) < 7); const outside = admitted.filter((support) => ["outside", "expanded"].includes(support.scopeStatus));
    const integrity = admitted.filter((support) => finite(support.integrity, 100) < 90 || (support.custodyIssues || []).length); const completedPhases = new Set((caseRecord.phases || []).filter((phase) => phase.completedAt != null).map((phase) => phase.id));
    const proceduralMissing = ["prosecution", "defense", "deliberation", "sentencing"].filter((phase) => !completedPhases.has(phase)); const capitalSupport = admitted.filter((support) => ["death", "killed", "fatal", "mass casualty", "soul destruction", "genocide"].some((pattern) => textOf(support).includes(pattern)));
    const counsel = caseRecord.counsel?.selected || proceeding.counsel?.options?.find((entry) => entry.id === proceeding.counsel?.selectedOptionId) || {}; const counselSkill = finite(counsel.proceduralSkill, 55); const preparation = finite(caseRecord.preparation?.progress);
    return CLAIMS.map((def) => {
      let baseScore = 0; const reasons = []; const recordRefs = [];
      if (def.id === "insufficientProof") { baseScore = clamp((9 - minimumMargin) * 8 + weakElements.length * 4, 0, 75); reasons.push(weakElements.length ? `${weakElements.length} required element(s) were proven by a narrow saved margin; the minimum margin was ${round(minimumMargin)}.` : "No required element has a narrow saved proof margin."); recordRefs.push(...weakElements.map((entry) => entry.id)); }
      if (def.id === "improperlyAdmittedEvidence") { baseScore = clamp(outside.length * 28 + (caseRecord.strategy?.challengeKind === "support" ? 8 : 0), 0, 80); reasons.push(outside.length ? `${outside.length} admitted support item(s) exceeded or expanded the saved authority scope.` : "The admitted record contains no support marked outside or expanded beyond scope."); recordRefs.push(...outside.map((entry) => entry.id)); }
      if (def.id === "brokenEvidenceIntegrity") { baseScore = clamp(integrity.reduce((total, support) => total + (100 - finite(support.integrity, 100)) / 2 + (support.custodyIssues || []).length * 12, 0), 0, 85); reasons.push(integrity.length ? `${integrity.length} admitted support item(s) retain saved integrity or custody defects.` : "The admitted record retains no evidence-integrity defect."); recordRefs.push(...integrity.map((entry) => entry.id)); }
      if (def.id === "proceduralError") { baseScore = clamp(proceduralMissing.length * 22 + ((caseRecord.history || []).some((entry) => /interrupted|denied/i.test(entry.summary)) ? 15 : 0), 0, 80); reasons.push(proceduralMissing.length ? `The record lacks completed entries for ${proceduralMissing.join(", ")}.` : "Every required trial and sentencing phase has a completed saved entry."); recordRefs.push(...proceduralMissing); }
      if (def.id === "unsupportedCapitalEligibility") { const exposure = finite(caseRecord.sentencing?.exposure); baseScore = clamp((32 - exposure) * 6 + (capitalSupport.length === 0 ? 60 : capitalSupport.length === 1 ? 8 : 0), 0, 90); reasons.push(`${capitalSupport.length} admitted support item(s) contain a saved capital-harm predicate; net exposure was ${round(exposure)}.`); recordRefs.push(...capitalSupport.map((entry) => entry.id), caseRecord.sentencing?.order?.id); }
      if (def.id === "ineffectiveRepresentation") { baseScore = clamp((55 - counselSkill) * 1.2 + (45 - preparation) * 0.8 + (counsel.kind === "self" ? 8 : 0), 0, 80); reasons.push(`Saved counsel skill was ${round(counselSkill)} and trial preparation was ${round(preparation)}.`); recordRefs.push(cleanId(counsel.id), caseRecord.id); }
      return normalizeClaim({ id: def.id, supported: baseScore >= 8, baseScore, reasons, recordRefs });
    });
  }

  function normalizeRecord(value, index = 0) {
    const source = value && typeof value === "object" ? value : {}; const openedAt = Math.max(0, finite(source.openedAt));
    return {
      id: cleanId(source.id) || `capital-appeal-${index + 1}`, stayId: cleanId(source.stayId), predecessorCaseId: cleanId(source.predecessorCaseId), orderId: cleanId(source.orderId), docket: String(source.docket || "Capital appeal").trim(), status: ["active", "reliefOrdered", "final"].includes(source.status) ? source.status : "active", openedAt,
      panel: (Array.isArray(source.panel) ? source.panel : []).map(normalizePanelMember), claims: (Array.isArray(source.claims) ? source.claims : []).map(normalizeClaim),
      calendar: { automaticReviewAt: Math.max(openedAt, finite(source.calendar?.automaticReviewAt, openedAt + 3 * DAY)), directAppealDeadlineAt: Math.max(openedAt, finite(source.calendar?.directAppealDeadlineAt, openedAt + DIRECT_APPEAL_DEADLINE)), finalAdverseDecisionAt: source.calendar?.finalAdverseDecisionAt == null ? null : Math.max(openedAt, finite(source.calendar.finalAdverseDecisionAt)), earliestExecutionAt: source.calendar?.earliestExecutionAt == null ? null : Math.max(openedAt, finite(source.calendar.earliestExecutionAt)) },
      automaticReview: { status: ["scheduled", "pending", "affirmed", "relief"].includes(source.automaticReview?.status) ? source.automaticReview.status : "scheduled", openedAt: source.automaticReview?.openedAt == null ? null : Math.max(openedAt, finite(source.automaticReview.openedAt)), decisionAt: source.automaticReview?.decisionAt == null ? null : Math.max(openedAt, finite(source.automaticReview.decisionAt)), outcome: normalizeOutcome(source.automaticReview?.outcome) },
      directAppeal: normalizeFiling(source.directAppeal), execution: { stayed: Boolean(source.execution?.stayed), stayKind: cleanId(source.execution?.stayKind), stayedAt: source.execution?.stayedAt == null ? null : Math.max(openedAt, finite(source.execution.stayedAt)), liftedAt: source.execution?.liftedAt == null ? null : Math.max(openedAt, finite(source.execution.liftedAt)), executionAt: Math.max(openedAt, finite(source.execution?.executionAt, openedAt + 30 * DAY)) },
      successorCase: source.successorCase && typeof source.successorCase === "object" ? { id: cleanId(source.successorCase.id), kind: cleanId(source.successorCase.kind), status: cleanId(source.successorCase.status) || "transferRequired", predecessorCaseId: cleanId(source.successorCase.predecessorCaseId), scheduledAt: Math.max(openedAt, finite(source.successorCase.scheduledAt)), excludedSupportIds: unique(source.successorCase.excludedSupportIds), trialCaseId: cleanId(source.successorCase.trialCaseId) } : null,
      decision: normalizeDecision(source.decision), history: normalizeHistory(source.history)
    };
  }
  function defaultState() { return { version: VERSION, records: [], nextRecordNumber: 1, nextSuccessorNumber: 1 }; }
  function normalizeState(value) { const source = value && typeof value === "object" ? value : {}; const records = (Array.isArray(source.records) ? source.records : []).map(normalizeRecord); return { version: VERSION, records, nextRecordNumber: Math.max(1, Math.floor(finite(source.nextRecordNumber, records.length + 1))), nextSuccessorNumber: Math.max(1, Math.floor(finite(source.nextSuccessorNumber, 1))) }; }
  function recordForStay(value, stayId) { return normalizeState(value).records.find((record) => record.stayId === cleanId(stayId)) || null; }

  function open(value, options = {}) {
    const state = normalizeState(value); const stayId = cleanId(options.stayId); const existing = state.records.find((record) => record.stayId === stayId); if (existing) return { state, record: existing, created: false };
    const openedAt = Math.max(0, finite(options.clock)); const id = `capital-appeal-${state.nextRecordNumber++}`; const seed = `${options.seed || "world"}:${id}`;
    const panel = [0, 1, 2].map((index) => ({ id: `${id}-judge-${index + 1}`, name: actorName(seed, index), role: index === 0 ? "presidingAppellateJudge" : "appellateJudge", proceduralStrictness: 48 + hash(`${seed}:${index}:strict`) % 34 }));
    const record = normalizeRecord({ id, stayId, predecessorCaseId: options.caseRecord?.id, orderId: options.caseRecord?.sentencing?.order?.id, docket: options.caseRecord?.docket, openedAt, panel, claims: claimInputs(options.caseRecord, options.proceeding), calendar: { automaticReviewAt: options.automaticReviewAt, directAppealDeadlineAt: openedAt + DIRECT_APPEAL_DEADLINE }, execution: { executionAt: options.executionAt }, history: [{ at: openedAt, action: "appealDocketOpened", summary: "A linked capital appellate docket opened without changing the original judgment record." }, { at: openedAt, action: "panelAssigned", summary: `Three named appellate judges were assigned; direct appeal must be filed by day ten after capital intake.` }] });
    state.records.push(record); return { state, record, created: true };
  }

  function scoreClaim(record, claimId, frozen, automatic = false) {
    const claim = record.claims.find((entry) => entry.id === claimId); if (!claim?.supported) return { claim, score: 0, factors: [{ label: "Record support", score: 0, reason: claim?.reasons[0] || "The claim is not supported by the saved record." }] };
    const factors = [{ label: "Record support", score: claim.baseScore, reason: claim.reasons.join(" ") }];
    const counsel = automatic ? 5 : clamp(finite(frozen?.counselSkill) / 12, 0, 8); factors.push({ label: automatic ? "Mandatory review scrutiny" : "Counsel presentation", score: counsel, reason: automatic ? "Automatic capital review applies a fixed record-scrutiny contribution." : `Frozen counsel skill was ${round(frozen?.counselSkill)}.` });
    const preparation = automatic ? 0 : clamp(finite(frozen?.legalPreparationDays) * 2, 0, 10); factors.push({ label: "Capital legal preparation", score: preparation, reason: `${round(frozen?.legalPreparationDays)} saved day(s) of capital legal preparation were frozen at filing.` });
    const preserved = automatic ? 0 : frozen?.preserved ? 5 : 0; factors.push({ label: "Issue preservation", score: preserved, reason: preserved ? "The original strategy preserved appellate issues." : "The issue was not specially preserved in the original strategy." });
    return { claim, score: round(factors.reduce((total, factor) => total + factor.score, 0)), factors };
  }
  function outcomeFor(record, claimIds, frozen, decidedAt, automatic = false) {
    const scored = claimIds.map((claimId) => scoreClaim(record, claimId, frozen, automatic)).filter((entry) => entry.claim).sort((left, right) => right.score - left.score || left.claim.id.localeCompare(right.claim.id)); const strongest = scored[0];
    if (!strongest || strongest.score < 45) return normalizeOutcome({ kind: "affirmed", decidedAt, claimId: strongest?.claim?.id, summary: "The appellate panel affirmed the capital judgment and sentence.", reasons: [...(strongest?.factors || []).map((factor) => `${factor.label}: ${round(factor.score)} — ${factor.reason}`), `${round(strongest?.score || 0)} did not meet the 45-point material-error threshold.`] });
    let kind = strongest.claim.remedy === "sentenceReversal" ? "sentenceReversal" : "convictionReversal"; if (strongest.claim.id === "insufficientProof" && strongest.score >= 60) kind = "finalReversalRelease";
    const successorKind = kind === "sentenceReversal" ? "resentencing" : kind === "convictionReversal" ? "retrial" : "release"; const excludedSupportIds = ["improperlyAdmittedEvidence", "brokenEvidenceIntegrity"].includes(strongest.claim.id) ? strongest.claim.recordRefs : [];
    return normalizeOutcome({ kind, decidedAt, claimId: strongest.claim.id, successorKind, excludedSupportIds, summary: kind === "sentenceReversal" ? "The panel vacated the death sentence and ordered a linked noncapital resentencing." : kind === "convictionReversal" ? "The panel reversed the conviction and authorized a linked retrial." : "The panel entered a final reversal requiring physical release.", reasons: [...strongest.factors.map((factor) => `${factor.label}: ${round(factor.score)} — ${factor.reason}`), `${round(strongest.score)} met the 45-point material-error threshold.`] });
  }
  function applyOutcome(state, record, filing, outcome, clock) {
    filing.outcome = outcome; filing.status = outcome.kind === "affirmed" ? "affirmed" : "relief"; record.execution.stayed = false; record.execution.liftedAt = clock;
    if (outcome.kind === "affirmed") { record.history.push({ at: clock, action: "judgmentAffirmed", summary: outcome.summary }); return; }
    record.status = "reliefOrdered"; record.successorCase = { id: `capital-successor-${state.nextSuccessorNumber++}`, kind: outcome.successorKind, status: "transferRequired", predecessorCaseId: record.predecessorCaseId, scheduledAt: clock + 2 * HOUR, excludedSupportIds: outcome.excludedSupportIds, trialCaseId: "" }; record.history.push({ at: clock, action: "appellateRelief", summary: `${outcome.summary} The original judgment remains preserved and a linked successor record was created.` });
  }
  function preservePendingStay(record) { if (record.status !== "active") return; if (record.directAppeal.status === "filed") { record.execution.stayed = true; record.execution.stayKind = "timelyDirectAppeal"; } else if (record.automaticReview.status === "pending") { record.execution.stayed = true; record.execution.stayKind = "automaticReview"; } }
  function finalizeAdverse(record, decidedAt) { record.status = "final"; record.calendar.finalAdverseDecisionAt = decidedAt; record.calendar.earliestExecutionAt = Math.max(record.execution.executionAt, decidedAt + MINIMUM_POST_ADVERSE_DELAY); record.execution.executionAt = record.calendar.earliestExecutionAt; record.execution.stayed = false; record.execution.liftedAt = decidedAt; }
  function fileDirectAppeal(value, recordId, options = {}, clock = 0) {
    const state = normalizeState(value); const record = state.records.find((entry) => entry.id === cleanId(recordId)); const at = Math.max(0, finite(clock)); const primary = record?.claims.find((claim) => claim.id === cleanId(options.primaryClaimId)); const secondary = record?.claims.find((claim) => claim.id === cleanId(options.secondaryClaimId));
    if (!record || record.status !== "active" || record.directAppeal.status !== "available" || at > record.calendar.directAppealDeadlineAt || !primary?.supported || (options.secondaryClaimId && (!secondary?.supported || secondary.id === primary.id))) return { state, record, changed: false, reason: "A timely appeal requires one supported primary claim and at most one distinct supported secondary claim." };
    record.directAppeal = normalizeFiling({ status: "filed", filedAt: at, decisionAt: at + DIRECT_DECISION_DELAY, primaryClaimId: primary.id, secondaryClaimId: secondary?.id, frozen: { counselName: String(options.counselName || "Capital appellate counsel"), counselSkill: clamp(options.counselSkill ?? 55, 0, 100), legalPreparationDays: Math.max(0, finite(options.legalPreparationDays)), preserved: Boolean(options.preserved), claimSnapshots: [primary, secondary].filter(Boolean).map(clone) } }); record.execution.stayed = true; record.execution.stayKind = "timelyDirectAppeal"; record.execution.stayedAt = at; record.decision = { required: true, kind: "directAppealFiled", reason: `The timely direct appeal stayed execution pending a written decision at ${record.directAppeal.decisionAt}.`, raisedAt: at }; record.history.push({ at, action: "directAppealFiled", summary: `${primary.label}${secondary ? ` and ${secondary.label}` : ""} were frozen with counsel, preparation, and preservation inputs.` }); return { state, record, changed: true };
  }
  function clearDecision(value, recordId) { const state = normalizeState(value); const record = state.records.find((entry) => entry.id === cleanId(recordId)); if (!record?.decision.required) return { state, record, changed: false }; record.decision = normalizeDecision({}); return { state, record, changed: true }; }
  function markSuccessor(value, recordId, options = {}, clock = 0) { const state = normalizeState(value); const record = state.records.find((entry) => entry.id === cleanId(recordId)); if (!record?.successorCase) return { state, record, changed: false }; record.successorCase.status = cleanId(options.status) || record.successorCase.status; if (options.trialCaseId) record.successorCase.trialCaseId = cleanId(options.trialCaseId); record.history.push({ at: Math.max(record.openedAt, finite(clock)), action: "successorCase", summary: String(options.summary || `Linked successor case is now ${record.successorCase.status}.`).trim() }); return { state, record, changed: true }; }

  function advance(value, clock = 0) {
    const state = normalizeState(value); const at = Math.max(0, finite(clock)); const events = [];
    for (const record of state.records.filter((entry) => entry.status === "active")) {
      if (record.automaticReview.status === "scheduled" && at >= record.calendar.automaticReviewAt) { record.automaticReview.status = "pending"; record.automaticReview.openedAt = record.calendar.automaticReviewAt; record.automaticReview.decisionAt = record.calendar.automaticReviewAt + AUTOMATIC_DECISION_DELAY; record.execution.stayed = true; record.execution.stayKind = "automaticReview"; record.execution.stayedAt = record.calendar.automaticReviewAt; record.decision = { required: true, kind: "automaticReviewOpened", reason: `Automatic capital review opened before ${record.panel.map((judge) => judge.name).join(", ")}; execution is stayed until the written decision.`, raisedAt: record.calendar.automaticReviewAt }; record.history.push({ at: record.calendar.automaticReviewAt, action: "automaticReviewOpened", summary: record.decision.reason }); events.push("automaticReviewOpened"); }
      if (record.automaticReview.status === "pending" && at >= record.automaticReview.decisionAt) { const automaticClaimIds = ["insufficientProof", "proceduralError", "unsupportedCapitalEligibility"].filter((id) => record.claims.find((claim) => claim.id === id)?.supported); const outcome = outcomeFor(record, automaticClaimIds, {}, record.automaticReview.decisionAt, true); applyOutcome(state, record, record.automaticReview, outcome, record.automaticReview.decisionAt); record.automaticReview.status = outcome.kind === "affirmed" ? "affirmed" : "relief"; if (outcome.kind === "affirmed" && record.directAppeal.status === "affirmed") finalizeAdverse(record, outcome.decidedAt); else preservePendingStay(record); record.decision = { required: true, kind: outcome.kind === "affirmed" ? "automaticReviewAffirmed" : "appellateReliefOrdered", reason: outcome.summary, raisedAt: outcome.decidedAt }; events.push(record.decision.kind); }
      if (record.status !== "active") continue;
      if (record.directAppeal.status === "filed" && at >= record.directAppeal.decisionAt) { const outcome = outcomeFor(record, [record.directAppeal.primaryClaimId, record.directAppeal.secondaryClaimId].filter(Boolean), record.directAppeal.frozen, record.directAppeal.decisionAt, false); applyOutcome(state, record, record.directAppeal, outcome, record.directAppeal.decisionAt); if (outcome.kind === "affirmed" && record.automaticReview.status === "affirmed") finalizeAdverse(record, outcome.decidedAt); else preservePendingStay(record); record.decision = { required: true, kind: outcome.kind === "affirmed" ? "directAppealAffirmed" : "appellateReliefOrdered", reason: outcome.summary, raisedAt: outcome.decidedAt }; events.push(record.decision.kind); }
      if (record.status === "active" && record.directAppeal.status === "available" && at >= record.calendar.directAppealDeadlineAt) { record.directAppeal.status = "deadlineMissed"; record.status = "final"; record.calendar.finalAdverseDecisionAt = record.calendar.directAppealDeadlineAt; record.calendar.earliestExecutionAt = Math.max(record.execution.executionAt, record.calendar.directAppealDeadlineAt + MINIMUM_POST_ADVERSE_DELAY); record.execution.executionAt = record.calendar.earliestExecutionAt; record.execution.stayed = false; record.execution.liftedAt = record.calendar.directAppealDeadlineAt; record.decision = { required: true, kind: "directAppealDeadlineMissed", reason: `The ordinary direct-appeal deadline passed. Execution cannot begin before ${record.calendar.earliestExecutionAt}; emergency relief requires genuinely new support or law.`, raisedAt: record.calendar.directAppealDeadlineAt }; record.history.push({ at: record.calendar.directAppealDeadlineAt, action: "directAppealDeadlineMissed", summary: record.decision.reason }); events.push("directAppealDeadlineMissed"); }
    }
    return { state, events, changed: events.length > 0 };
  }
  function nextEvent(value, clock = 0) { const at = finite(clock); const events = []; for (const record of normalizeState(value).records.filter((entry) => entry.status === "active" && !entry.decision.required)) { if (record.automaticReview.status === "scheduled") events.push({ at: record.calendar.automaticReviewAt, kind: "automaticReview", recordId: record.id, label: `${record.docket} automatic capital review` }); if (record.automaticReview.status === "pending") events.push({ at: record.automaticReview.decisionAt, kind: "automaticDecision", recordId: record.id, label: `${record.docket} automatic-review decision` }); if (record.directAppeal.status === "available") events.push({ at: record.calendar.directAppealDeadlineAt, kind: "appealDeadline", recordId: record.id, label: `${record.docket} direct-appeal deadline` }); if (record.directAppeal.status === "filed") events.push({ at: record.directAppeal.decisionAt, kind: "appealDecision", recordId: record.id, label: `${record.docket} direct-appeal decision` }); } return events.filter((event) => event.at >= at).sort((left, right) => left.at - right.at || left.kind.localeCompare(right.kind))[0] || null; }

  return Object.freeze({ VERSION, HOUR, DAY, AUTOMATIC_DECISION_DELAY, DIRECT_APPEAL_DEADLINE, DIRECT_DECISION_DELAY, MINIMUM_POST_ADVERSE_DELAY, CLAIMS, defaultState, normalizeState, recordForStay, claimInputs, open, scoreClaim, outcomeFor, fileDirectAppeal, clearDecision, markSuccessor, advance, nextEvent });
}));
