(function attachHelixPrisonBreak(root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.HelixPrisonBreak = api;
}(typeof globalThis !== "undefined" ? globalThis : this, function createHelixPrisonBreak() {
  "use strict";

  const VERSION = 1;
  const HOUR = 3600;
  const DAY = 24 * HOUR;
  const FACT_DEFS = Object.freeze([
    { id: "countWindow", label: "Count-window timing", layer: "housing" },
    { id: "staffShiftGap", label: "Named shift gap", layer: "housing" },
    { id: "doorControlCircuit", label: "Door-control dependency", layer: "circulation" },
    { id: "credentialHandling", label: "Maintenance credential practice", layer: "circulation" },
    { id: "workshopToolAccess", label: "Workshop tool access", layer: "circulation" },
    { id: "intakeSearchProcedure", label: "Intake search procedure", layer: "intake" },
    { id: "vehicleGateSchedule", label: "Vehicle-gate service schedule", layer: "perimeter" },
    { id: "collarMechanism", label: "Collar lock and ward mechanism", layer: "suppression" }
  ]);
  const ASSET_DEFS = Object.freeze([
    { id: "latchShim", label: "Concealed latch-and-ward shim", physicalKey: "escapeBypassTool" },
    { id: "maintenanceCredential", label: "Copied maintenance credential", physicalKey: "prisonMaintenanceCredential" },
    { id: "maintenanceUniform", label: "Altered prison maintenance uniform", physicalKey: "prisonMaintenanceUniform" }
  ]);
  const PREPARATION_DEFS = Object.freeze([
    { id: "observeCount", label: "Chart counts and the shift gap", roomId: "statePrisonHousing", durationMinutes: 60, grantsFactIds: ["countWindow", "staffShiftGap"], grantsAssetIds: [], requiredFactIds: [], relationshipRequired: false },
    { id: "studyDoorRecords", label: "Trace the door-control dependency", roomId: "statePrisonProgram", durationMinutes: 90, grantsFactIds: ["doorControlCircuit"], grantsAssetIds: [], requiredFactIds: [], relationshipRequired: false },
    { id: "observeWorkshop", label: "Observe credentials and tool control", roomId: "statePrisonWorkshop", durationMinutes: 75, grantsFactIds: ["credentialHandling", "workshopToolAccess"], grantsAssetIds: [], requiredFactIds: [], relationshipRequired: false },
    { id: "traceVehicleSchedule", label: "Reconstruct intake and vehicle schedules", roomId: "statePrisonCommunications", durationMinutes: 90, grantsFactIds: ["intakeSearchProcedure", "vehicleGateSchedule"], grantsAssetIds: [], requiredFactIds: [], relationshipRequired: false },
    { id: "examineCollar", label: "Examine the collar during clinic access", roomId: "statePrisonClinic", durationMinutes: 60, grantsFactIds: ["collarMechanism"], grantsAssetIds: [], requiredFactIds: [], relationshipRequired: false },
    { id: "fabricateShim", label: "Fabricate a concealed latch-and-ward shim", roomId: "statePrisonWorkshop", durationMinutes: 120, grantsFactIds: [], grantsAssetIds: ["latchShim"], requiredFactIds: ["workshopToolAccess"], relationshipRequired: false },
    { id: "secureDisguise", label: "Secure a credential and maintenance disguise", roomId: "statePrisonDayroom", durationMinutes: 90, grantsFactIds: [], grantsAssetIds: ["maintenanceCredential", "maintenanceUniform"], requiredFactIds: ["credentialHandling"], relationshipRequired: true }
  ]);
  const COLLAR_STRATEGIES = Object.freeze([
    { id: "keepLocked", label: "Escape with collar locked", description: "Lowest immediate collar risk; magic remains completely suppressed after escape." },
    { id: "tamperInside", label: "Disable collar inside prison", description: "Adds a dangerous physical stage but restores magic if it succeeds." },
    { id: "removeAfter", label: "Prepare removal after escape", description: "Carry the active collar out, then attempt physical removal at fugitive staging." }
  ]);
  const REQUIRED_FACT_IDS = Object.freeze(["countWindow", "staffShiftGap", "doorControlCircuit", "credentialHandling", "vehicleGateSchedule"]);
  const REQUIRED_ASSET_IDS = Object.freeze(["latchShim", "maintenanceCredential", "maintenanceUniform"]);
  const BASE_STAGES = Object.freeze([
    { id: "leaveHousing", label: "Slip out during the count-and-shift gap", layer: "housing", roomId: "statePrisonHousing", destinationRoomId: "statePrisonCorridor", durationMinutes: 20, baseDetection: 14, helpfulFactIds: ["countWindow", "staffShiftGap"] },
    { id: "crossCirculation", label: "Cross secure circulation in maintenance disguise", layer: "circulation", roomId: "statePrisonCorridor", destinationRoomId: "statePrisonControl", durationMinutes: 25, baseDetection: 18, helpfulFactIds: ["credentialHandling", "doorControlCircuit"] },
    { id: "passControl", label: "Bypass prison control", layer: "control", roomId: "statePrisonControl", destinationRoomId: "statePrisonIntake", durationMinutes: 30, baseDetection: 24, helpfulFactIds: ["doorControlCircuit", "intakeSearchProcedure"] },
    { id: "clearVehicleGate", label: "Clear intake and the vehicle gate", layer: "perimeter", roomId: "statePrisonIntake", destinationRoomId: "correctionalServiceRoad", durationMinutes: 25, baseDetection: 22, helpfulFactIds: ["intakeSearchProcedure", "vehicleGateSchedule"] }
  ]);

  function finite(value, fallback = 0) { const number = Number(value); return Number.isFinite(number) ? number : fallback; }
  function cleanId(value) { return String(value || "").trim().replace(/[^a-zA-Z0-9:_-]/g, ""); }
  function clamp(value, minimum = 0, maximum = 100) { return Math.max(minimum, Math.min(maximum, finite(value))); }
  function uniqueIds(candidate) { return [...new Set((Array.isArray(candidate) ? candidate : []).map(cleanId).filter(Boolean))]; }
  function clone(value) { return value == null ? value : JSON.parse(JSON.stringify(value)); }
  function hash(seed) { let value = 2166136261; for (const character of String(seed || "prison-break")) { value ^= character.charCodeAt(0); value = Math.imul(value, 16777619); } return value >>> 0; }
  function unit(seed) { return hash(seed) / 4294967295; }
  function riskBand(value) { return value >= 70 ? "critical" : value >= 45 ? "high" : value >= 22 ? "moderate" : "low"; }
  function normalizeHistory(candidate) { return (Array.isArray(candidate) ? candidate : []).map((entry) => ({ at: Math.max(0, finite(entry?.at)), action: cleanId(entry?.action) || "updated", summary: String(entry?.summary || "Prison-break state updated.").trim() })).sort((a, b) => a.at - b.at); }
  function normalizePreparation(candidate, index = 0) {
    return { id: cleanId(candidate?.id) || `prison-preparation-${index + 1}`, actionId: cleanId(candidate?.actionId), actorId: cleanId(candidate?.actorId), startedAt: Math.max(0, finite(candidate?.startedAt)), dueAt: Math.max(0, finite(candidate?.dueAt)), completedAt: candidate?.completedAt == null ? null : Math.max(0, finite(candidate.completedAt)), status: ["active", "completed", "interrupted"].includes(candidate?.status) ? candidate.status : "active", grantsFactIds: uniqueIds(candidate?.grantsFactIds), grantsAssetIds: uniqueIds(candidate?.grantsAssetIds), summary: String(candidate?.summary || "").trim() };
  }
  function normalizeAsset(candidate, index = 0) { const def = ASSET_DEFS.find((entry) => entry.id === candidate?.id) || ASSET_DEFS[index] || ASSET_DEFS[0]; return { id: def.id, label: def.label, physicalKey: def.physicalKey, acquiredAt: Math.max(0, finite(candidate?.acquiredAt)), sourceActionId: cleanId(candidate?.sourceActionId), actorId: cleanId(candidate?.actorId), status: ["held", "used", "confiscated", "lost"].includes(candidate?.status) ? candidate.status : "held", physicalStackId: cleanId(candidate?.physicalStackId) }; }
  function normalizeStage(candidate, index = 0) {
    return { id: cleanId(candidate?.id) || `prison-break-stage-${index + 1}`, label: String(candidate?.label || "Escape stage").trim(), layer: cleanId(candidate?.layer), roomId: cleanId(candidate?.roomId), destinationRoomId: cleanId(candidate?.destinationRoomId), durationMinutes: Math.max(1, finite(candidate?.durationMinutes, 20)), helpfulFactIds: uniqueIds(candidate?.helpfulFactIds), status: ["pending", "active", "completed", "detected"].includes(candidate?.status) ? candidate.status : "pending", startedAt: candidate?.startedAt == null ? null : Math.max(0, finite(candidate.startedAt)), completedAt: candidate?.completedAt == null ? null : Math.max(0, finite(candidate.completedAt)), baseDetection: clamp(candidate?.baseDetection), detectionChance: clamp(candidate?.detectionChance, 0, 95), exposure: clamp(candidate?.exposure), roll: clamp(candidate?.roll, 0, 1), detected: Boolean(candidate?.detected), reason: String(candidate?.reason || "").trim() };
  }
  function normalizeAttempt(candidate, index = 0) {
    const createdAt = Math.max(0, finite(candidate?.createdAt));
    return { id: cleanId(candidate?.id) || `prison-break-attempt-${index + 1}`, recordId: cleanId(candidate?.recordId), stayId: cleanId(candidate?.stayId), caseId: cleanId(candidate?.caseId), proceedingId: cleanId(candidate?.proceedingId), status: ["planned", "active", "escaped", "captured", "abandoned"].includes(candidate?.status) ? candidate.status : "planned", createdAt, startedAt: candidate?.startedAt == null ? null : Math.max(createdAt, finite(candidate.startedAt)), endedAt: candidate?.endedAt == null ? null : Math.max(createdAt, finite(candidate.endedAt)), collarStrategyId: COLLAR_STRATEGIES.some((entry) => entry.id === candidate?.collarStrategyId) ? candidate.collarStrategyId : "keepLocked", collarStatus: ["locked", "disabled", "removed"].includes(candidate?.collarStatus) ? candidate.collarStatus : "locked", frozen: candidate?.frozen && typeof candidate.frozen === "object" ? clone(candidate.frozen) : {}, stages: (Array.isArray(candidate?.stages) ? candidate.stages : []).map(normalizeStage), currentStageIndex: Math.max(0, Math.floor(finite(candidate?.currentStageIndex))), risk: clamp(candidate?.risk), riskBand: riskBand(candidate?.risk), destinationId: cleanId(candidate?.destinationId) || "correctionalServiceRoad", consequences: (Array.isArray(candidate?.consequences) ? candidate.consequences : []).map(String), pursuit: { status: ["none", "watchingLab", "searching", "recaptureScheduled"].includes(candidate?.pursuit?.status) ? candidate.pursuit.status : "none", alert: clamp(candidate?.pursuit?.alert), searchBeginsAt: candidate?.pursuit?.searchBeginsAt == null ? null : Math.max(0, finite(candidate.pursuit.searchBeginsAt)), labWatch: Boolean(candidate?.pursuit?.labWatch), evidenceId: cleanId(candidate?.pursuit?.evidenceId) }, collarRemoval: { status: ["unavailable", "available", "active", "completed", "failed"].includes(candidate?.collarRemoval?.status) ? candidate.collarRemoval.status : "unavailable", startedAt: candidate?.collarRemoval?.startedAt == null ? null : Math.max(0, finite(candidate.collarRemoval.startedAt)), completedAt: candidate?.collarRemoval?.completedAt == null ? null : Math.max(0, finite(candidate.collarRemoval.completedAt)), roll: clamp(candidate?.collarRemoval?.roll, 0, 1), injury: String(candidate?.collarRemoval?.injury || "").trim() }, history: normalizeHistory(candidate?.history) };
  }
  function normalizeRecord(candidate, index = 0) {
    const openedAt = Math.max(0, finite(candidate?.openedAt));
    return { id: cleanId(candidate?.id) || `prison-break-record-${index + 1}`, stayId: cleanId(candidate?.stayId), caseId: cleanId(candidate?.caseId), proceedingId: cleanId(candidate?.proceedingId), docket: String(candidate?.docket || "Prison escape record").trim(), openedAt, factIds: uniqueIds(candidate?.factIds).filter((id) => FACT_DEFS.some((entry) => entry.id === id)), assets: (Array.isArray(candidate?.assets) ? candidate.assets : []).map(normalizeAsset), preparations: (Array.isArray(candidate?.preparations) ? candidate.preparations : []).map(normalizePreparation), attemptIds: uniqueIds(candidate?.attemptIds), history: normalizeHistory(candidate?.history) };
  }
  function defaultState() { return { version: VERSION, records: [], attempts: [], nextRecordNumber: 1, nextPreparationNumber: 1, nextAttemptNumber: 1 }; }
  function normalizeState(candidate) { const source = candidate && typeof candidate === "object" ? candidate : {}; const records = (Array.isArray(source.records) ? source.records : []).map(normalizeRecord); const attempts = (Array.isArray(source.attempts) ? source.attempts : []).map(normalizeAttempt); return { version: VERSION, records, attempts, nextRecordNumber: Math.max(1, Math.floor(finite(source.nextRecordNumber, records.length + 1))), nextPreparationNumber: Math.max(1, Math.floor(finite(source.nextPreparationNumber, 1))), nextAttemptNumber: Math.max(1, Math.floor(finite(source.nextAttemptNumber, attempts.length + 1))) }; }
  function recordForStay(candidate, stayId) { return normalizeState(candidate).records.find((entry) => entry.stayId === cleanId(stayId)) || null; }
  function activeAttempt(candidate) { return normalizeState(candidate).attempts.find((entry) => ["planned", "active"].includes(entry.status)) || null; }
  function latestEscape(candidate) { return [...normalizeState(candidate).attempts].reverse().find((entry) => entry.status === "escaped") || null; }
  function open(candidate, stay, options = {}) { const state = normalizeState(candidate); const existing = state.records.find((entry) => entry.stayId === cleanId(stay?.id)); if (existing) return { state, record: existing, created: false }; if (!stay?.id) return { state, record: null, created: false }; const id = `prison-break-record-${state.nextRecordNumber++}`; const record = normalizeRecord({ id, stayId: stay.id, caseId: stay.caseId, proceedingId: options.proceedingId, docket: stay.docket, openedAt: options.clock, history: [{ at: options.clock, action: "opened", summary: "The prison received a persistent security-study and escape-preparation record." }] }); state.records.push(record); return { state, record, created: true }; }

  function preparationAvailability(recordCandidate, actionId, options = {}) {
    const record = normalizeRecord(recordCandidate); const action = PREPARATION_DEFS.find((entry) => entry.id === cleanId(actionId));
    if (!action) return { available: false, reason: "Unknown preparation action." };
    if (record.preparations.some((entry) => entry.actionId === action.id && entry.status === "active")) return { available: false, reason: "This concrete preparation is already active." };
    const completed = record.preparations.some((entry) => entry.actionId === action.id && entry.status === "completed");
    const missingGrantedAsset = action.grantsAssetIds.some((id) => !record.assets.some((asset) => asset.id === id && asset.status === "held"));
    if (completed && !missingGrantedAsset) return { available: false, reason: "This concrete fact or held asset is already recorded." };
    const missing = action.requiredFactIds.filter((id) => !record.factIds.includes(id)); if (missing.length) return { available: false, reason: `Missing fact: ${missing.map((id) => FACT_DEFS.find((entry) => entry.id === id)?.label || id).join(", ")}.` };
    if (action.relationshipRequired && !cleanId(options.actorId)) return { available: false, reason: "A cooperative named prisoner must agree to help." };
    if (action.relationshipRequired && finite(options.relationshipScore) < 20) return { available: false, reason: "The selected prisoner is not yet cooperative." };
    return { available: true, reason: "" };
  }
  function beginPreparation(candidate, recordId, actionId, options = {}) {
    const state = normalizeState(candidate); const record = state.records.find((entry) => entry.id === cleanId(recordId)); const action = PREPARATION_DEFS.find((entry) => entry.id === cleanId(actionId)); const availability = preparationAvailability(record, actionId, options); const at = Math.max(0, finite(options.clock));
    if (!record || !action || !availability.available || record.preparations.some((entry) => entry.status === "active")) return { state, record, preparation: null, changed: false, reason: availability.reason || "Another preparation is active." };
    const preparation = normalizePreparation({ id: `prison-preparation-${state.nextPreparationNumber++}`, actionId: action.id, actorId: options.actorId, startedAt: at, dueAt: at + action.durationMinutes * 60, status: "active", grantsFactIds: action.grantsFactIds, grantsAssetIds: action.grantsAssetIds }); record.preparations.push(preparation); record.history.push({ at, action: "preparationStarted", summary: `${action.label} began in ${action.roomId}.` }); return { state, record, preparation, action, changed: true };
  }
  function completePreparation(candidate, recordId, preparationId, clock = 0) {
    const state = normalizeState(candidate); const record = state.records.find((entry) => entry.id === cleanId(recordId)); const preparation = record?.preparations.find((entry) => entry.id === cleanId(preparationId)); const at = Math.max(0, finite(clock)); if (!record || !preparation || preparation.status !== "active" || at < preparation.dueAt) return { state, record, preparation, changed: false };
    preparation.status = "completed"; preparation.completedAt = at; for (const id of preparation.grantsFactIds) if (!record.factIds.includes(id)) record.factIds.push(id); for (const id of preparation.grantsAssetIds) if (!record.assets.some((entry) => entry.id === id && entry.status === "held")) record.assets.push(normalizeAsset({ id, acquiredAt: at, sourceActionId: preparation.actionId, actorId: preparation.actorId })); const action = PREPARATION_DEFS.find((entry) => entry.id === preparation.actionId); preparation.summary = `${action?.label || preparation.actionId} completed; ${preparation.grantsFactIds.length} fact(s) and ${preparation.grantsAssetIds.length} asset(s) became available.`; record.history.push({ at, action: "preparationCompleted", summary: preparation.summary }); return { state, record, preparation, action, changed: true };
  }
  function setAssetPhysicalStack(candidate, recordId, assetId, stackId) { const state = normalizeState(candidate); const record = state.records.find((entry) => entry.id === cleanId(recordId)); const asset = record?.assets.find((entry) => entry.id === cleanId(assetId) && entry.status === "held"); if (!asset) return { state, record, asset, changed: false }; asset.physicalStackId = cleanId(stackId); return { state, record, asset, changed: true }; }

  function planAvailability(recordCandidate, collarStrategyId) { const record = normalizeRecord(recordCandidate); const strategy = COLLAR_STRATEGIES.find((entry) => entry.id === cleanId(collarStrategyId)); const missingFactIds = REQUIRED_FACT_IDS.filter((id) => !record.factIds.includes(id)); const missingAssetIds = REQUIRED_ASSET_IDS.filter((id) => !record.assets.some((asset) => asset.id === id && asset.status === "held" && asset.physicalStackId)); if (["tamperInside", "removeAfter"].includes(strategy?.id) && !record.factIds.includes("collarMechanism")) missingFactIds.push("collarMechanism"); return { available: Boolean(strategy && !missingFactIds.length && !missingAssetIds.length), strategy, missingFactIds, missingAssetIds, reason: !strategy ? "Choose a valid collar strategy." : missingFactIds.length ? `Missing facts: ${missingFactIds.join(", ")}.` : missingAssetIds.length ? `Missing physical assets: ${missingAssetIds.join(", ")}.` : "" }; }
  function plan(candidate, recordId, options = {}) {
    const state = normalizeState(candidate); const record = state.records.find((entry) => entry.id === cleanId(recordId)); const availability = planAvailability(record, options.collarStrategyId); const at = Math.max(0, finite(options.clock)); if (!record || !availability.available || activeAttempt(state)) return { state, record, attempt: null, changed: false, reason: availability.reason || "An escape attempt is already active." };
    const relationshipScore = clamp(options.relationshipScore, -100, 100); const standing = clamp(options.standing); const facts = [...record.factIds]; const assets = record.assets.filter((entry) => entry.status === "held").map((entry) => entry.id); const extraStage = availability.strategy.id === "tamperInside" ? [{ id: "disableCollar", label: "Tamper with the collar inside prison", layer: "suppression", roomId: "statePrisonHousing", destinationRoomId: "statePrisonHousing", durationMinutes: 30, baseDetection: 30, helpfulFactIds: ["collarMechanism"] }] : [];
    const stageDefs = [...extraStage, ...BASE_STAGES]; const riskReduction = Math.min(8, standing / 15) + Math.max(0, relationshipScore) / 12; const id = `prison-break-attempt-${state.nextAttemptNumber++}`;
    const stages = stageDefs.map((stage, index) => normalizeStage({ ...stage, detectionChance: clamp(stage.baseDetection - stage.helpfulFactIds.filter((factId) => facts.includes(factId)).length * 3 - riskReduction, 3, 90), roll: unit(`${options.seed}:${id}:${stage.id}:${index}`) })); const risk = stages.reduce((sum, stage) => sum + stage.detectionChance, 0) / stages.length;
    const attempt = normalizeAttempt({ id, recordId: record.id, stayId: record.stayId, caseId: record.caseId, proceedingId: record.proceedingId, status: "planned", createdAt: at, collarStrategyId: availability.strategy.id, collarStatus: "locked", frozen: { factIds: facts, assetIds: assets, assistingActorId: options.assistingActorId, assistingActorName: options.assistingActorName, relationshipScore, standing, sentenceServedSeconds: Math.max(0, finite(options.sentenceServedSeconds)), unservedSentenceSeconds: Math.max(0, finite(options.unservedSentenceSeconds)), routeLabel: "Maintenance-disguise vehicle-gate escape" }, stages, risk, destinationId: "correctionalServiceRoad", collarRemoval: { status: availability.strategy.id === "removeAfter" ? "available" : "unavailable", roll: unit(`${options.seed}:${id}:collar-removal`) }, history: [{ at, action: "planned", summary: `Maintenance-disguise escape launched with ${facts.length} frozen fact(s), ${assets.length} physical asset(s), ${riskBand(risk)} qualitative risk, and ${availability.strategy.label}.` }] }); state.attempts.push(attempt); record.attemptIds.push(attempt.id); for (const asset of record.assets.filter((entry) => REQUIRED_ASSET_IDS.includes(entry.id) && entry.status === "held")) asset.status = "used"; return { state, record, attempt, changed: true };
  }
  function beginStage(candidate, attemptId, options = {}) { const state = normalizeState(candidate); const attempt = state.attempts.find((entry) => entry.id === cleanId(attemptId)); const stage = attempt?.stages[attempt?.currentStageIndex || 0]; if (!attempt || !stage || !["planned", "active"].includes(attempt.status) || stage.status !== "pending") return { state, attempt, stage, changed: false }; const at = Math.max(attempt.createdAt, finite(options.clock)); attempt.status = "active"; attempt.startedAt ??= at; stage.status = "active"; stage.startedAt = at; stage.exposure = clamp(options.officerExposure); stage.detectionChance = clamp(stage.detectionChance + stage.exposure / 4, 3, 95); stage.reason = `${riskBand(stage.detectionChance)} risk from frozen preparation and ${Math.round(stage.exposure)} actual officer exposure.`; attempt.history.push({ at, action: "stageStarted", summary: `${stage.label} began. ${stage.reason}` }); return { state, attempt, stage, changed: true }; }
  function completeStage(candidate, attemptId, clock = 0) { const state = normalizeState(candidate); const attempt = state.attempts.find((entry) => entry.id === cleanId(attemptId)); const stage = attempt?.stages[attempt?.currentStageIndex || 0]; const at = Math.max(0, finite(clock)); if (!attempt || !stage || stage.status !== "active") return { state, attempt, stage, changed: false }; stage.completedAt = at; stage.detected = stage.roll < stage.detectionChance / 100; if (stage.detected) { stage.status = "detected"; attempt.status = "captured"; attempt.endedAt = at; attempt.consequences = ["Physical recapture", "Contraband confiscated", "Temporary segregation and privilege restriction", "Evidence-linked attempted-escape referral"]; attempt.history.push({ at, action: "captured", summary: `${stage.label} was physically detected; the attempt ended in recapture without changing the court sentence.` }); return { state, attempt, stage, captured: true, changed: true }; } stage.status = "completed"; if (stage.id === "disableCollar") attempt.collarStatus = "disabled"; attempt.currentStageIndex += 1; if (attempt.currentStageIndex >= attempt.stages.length) { attempt.status = "escaped"; attempt.endedAt = at; attempt.pursuit = { status: "watchingLab", alert: clamp(60 + attempt.risk / 3), searchBeginsAt: at + HOUR, labWatch: true, evidenceId: "" }; attempt.history.push({ at, action: "escaped", summary: `Every physical security layer was cleared; ${attempt.frozen.unservedSentenceSeconds} second(s) of the original sentence remain unserved.` }); return { state, attempt, stage, escaped: true, changed: true }; } attempt.history.push({ at, action: "stageCompleted", summary: `${stage.label} completed; the next physical security layer remains pending.` }); return { state, attempt, stage, nextStage: attempt.stages[attempt.currentStageIndex], changed: true }; }
  function beginCollarRemoval(candidate, attemptId, clock = 0) { const state = normalizeState(candidate); const attempt = state.attempts.find((entry) => entry.id === cleanId(attemptId)); if (!attempt || attempt.status !== "escaped" || attempt.collarStatus !== "locked" || attempt.collarRemoval.status !== "available") return { state, attempt, changed: false }; attempt.collarRemoval.status = "active"; attempt.collarRemoval.startedAt = Math.max(0, finite(clock)); attempt.history.push({ at: attempt.collarRemoval.startedAt, action: "collarRemovalStarted", summary: "The scientist began a physical off-site collar-removal attempt using the carried shim and saved mechanism notes." }); return { state, attempt, changed: true }; }
  function completeCollarRemoval(candidate, attemptId, options = {}, clock = 0) { const state = normalizeState(candidate); const attempt = state.attempts.find((entry) => entry.id === cleanId(attemptId)); if (!attempt || attempt.collarRemoval.status !== "active") return { state, attempt, changed: false }; const at = Math.max(attempt.collarRemoval.startedAt, finite(clock)); const threshold = clamp(0.62 - clamp(options.analysisSkill) / 250, 0.22, 0.62); const success = attempt.collarRemoval.roll >= threshold; attempt.collarRemoval.status = success ? "completed" : "failed"; attempt.collarRemoval.completedAt = at; if (success) attempt.collarStatus = "removed"; else { attempt.collarRemoval.injury = "Nullstone ward backlash and neck injury"; attempt.pursuit.alert = clamp(attempt.pursuit.alert + 8); } attempt.history.push({ at, action: success ? "collarRemoved" : "collarRemovalFailed", summary: success ? "The prison collar was physically removed outside the facility." : "The off-site removal failed, caused a ward injury, and left the collar locked." }); return { state, attempt, success, changed: true }; }
  function recordReturn(candidate, attemptId, destinationId, clock = 0) { const state = normalizeState(candidate); const attempt = state.attempts.find((entry) => entry.id === cleanId(attemptId) && entry.status === "escaped"); if (!attempt || !["concealedExit", "publicEntrance"].includes(destinationId)) return { state, attempt, changed: false }; const at = Math.max(attempt.endedAt, finite(clock)); attempt.pursuit.status = "recaptureScheduled"; attempt.pursuit.alert = clamp(attempt.pursuit.alert + (destinationId === "publicEntrance" ? 25 : 14)); attempt.pursuit.labWatch = true; attempt.history.push({ at, action: "watchedReturn", summary: `The scientist deliberately returned through ${destinationId}; the saved prison bench warrant triggered a physical recapture response.` }); return { state, attempt, recaptureRequired: true, changed: true }; }

  return Object.freeze({ VERSION, HOUR, DAY, FACT_DEFS, ASSET_DEFS, PREPARATION_DEFS, COLLAR_STRATEGIES, REQUIRED_FACT_IDS, REQUIRED_ASSET_IDS, BASE_STAGES, defaultState, normalizeState, normalizeRecord, normalizeAttempt, recordForStay, activeAttempt, latestEscape, open, preparationAvailability, beginPreparation, completePreparation, setAssetPhysicalStack, planAvailability, plan, beginStage, completeStage, beginCollarRemoval, completeCollarRemoval, recordReturn, riskBand });
}));
