const { test, expect } = require('@playwright/test');
const City = require('../city-approach');
const Aid = require('../castaway-assistance');
const { pathToFileURL } = require('url');
const path = require('path');
const destination = { id: 'castaway-test', strategicCellId: 'planet-cell:00003', originCellId: 'planet-cell:00001', label: 'Camp', distanceKm: 90, temperatureC: 18, precipitationMm: 500, slopePercent: 10 };
async function setup(page, companions = []) {
  page.on('dialog', d => d.accept());
  await page.goto(pathToFileURL(path.resolve(__dirname, '..', 'index.html')).href);
  await page.evaluate(() => { localStorage.clear(); localStorage.setItem('helix-heresy-v1-preferences', JSON.stringify({ mapRendererMode: 'dom' })); });
  await page.reload();
  await page.evaluate(() => window.helixHeresyDebug.setSurveyExpeditionTestContext({ network: { homeDestinationId: 'site:lab', nearestSettlementDestinationId: 'city:a', routes: [], destinations: [
    { id: 'site:lab', kind: 'laboratorySite', cityId: 'a', label: 'Lab', cellId: 'planet-cell:00009', supportComponentId: 'one', known: true, localDistanceKm: 2, routeContinuity: 'municipal', dangerBand: 'veryLow' },
    { id: 'city:a', kind: 'fortifiedCity', cityId: 'a', label: 'Aster', cellId: 'planet-cell:00001', supportComponentId: 'one', known: true, jurisdiction: { kind: 'city', cityId: 'a' } }
  ] }, context: { worldId: 'test-world', siteId: 'lab-test', strategicCellId: 'planet-cell:00009', seed: 'penal-test', publicProspects: {}, truth: {} } }));
  const warrant = await page.evaluate(() => window.helixHeresyDebug.issueTestWarrant('law-enforcement', { immediate: true }));
  await page.evaluate(id => { const d = window.helixHeresyDebug; d.placeScientistAtRaidEntry(id); d.updateLawEnforcementRaids(1); d.surrenderToRaid(id); for (let i = 0; i < 8; i++) d.updateLawEnforcementRaids(1, { defer: i < 7 }); }, warrant.raidId);
  expect(await page.evaluate(({ destination, companions }) => window.helixHeresyDebug.preparePenalFlightForTest(destination, companions), { destination, companions })).toBe(true);
}

const provider = () => { const p = Aid.service({ id: 'contact' }, { id: 'pad', cellId: 'pad' }, 'Irena', 0); p.radioSeconds = 14400; return p; };
const gate = (capacityBand = 'functional') => City.gate({ id: 'gate', cityId: 'a', institutionId: 'civic-a', capacityBand, createdAt: 0,
  clerk: { id: 'clerk', mapCell: { x: 10, y: 6, z: 16 } }, guard: { id: 'guard', mapCell: { x: 12, y: 7, z: 16 } } });
const person = { id: 'scientist', sourceCityId: 'a', sourceOrderId: 'completed-order' };
const evidence = { present: true, sourceOrderId: 'completed-order', connection: true, recognition: 'domestic' };
test('checkpoint permission does not erase banishment, reopen punishment, or admit passengers', () => {
  const s = City.create(), p = provider(), g = gate(), t = City.request(s, g.id, p.id, [person], 60, 0);
  expect(City.offer(t, g, p, 120)).toBe(true); expect(City.checkpointAuthorized(t, 'scientist')).toBe(false);
  expect(City.accept(t, g, p, 10000, 121)).toBe(true); expect(City.checkpointAuthorized(t, 'scientist')).toBe(true);
  const bans = [{ personId: 'scientist', cityId: 'a', orderId: 'completed-order', status: 'active', recognizedBy: [] }];
  const before = JSON.stringify(bans), d = City.decision(person, g, evidence, bans, 300);
  expect(d.status).toBe('refused'); expect(d.reason).toContain('not reactivated'); expect(City.canEnter(d, true)).toBe(false); expect(JSON.stringify(bans)).toBe(before);
  t.permit.departedIds = ['scientist']; expect(City.checkpointAuthorized(t, 'scientist')).toBe(false);
});
test('foreign notices and bare recognition labels never become a local ban', () => {
  const g = gate(), b = { personId: 'scientist', cityId: 'foreign', status: 'active', orderId: 'foreign-order', recognizedBy: ['a'] };
  expect(City.decision(person, g, evidence, [b], 0).status).toBe('admitted');
  b.recognizedBy = [{ cityId: 'a', localOrderId: 'local-judicial-order', institutionId: 'judiciary-a', status: 'active' }];
  expect(City.decision(person, g, evidence, [b], 0).status).toBe('refused');
  expect(City.decision({ ...person, id: 'companion' }, g, evidence, [b], 0).status).toBe('admitted');
});
test('identity review is separate from admission and missing facts remain pending', () => {
  const g = gate();
  expect(City.decision(person, g, { ...evidence, present: false }, [], 0).status).toBe('pending');
  expect(City.decision(person, g, { ...evidence, connection: false }, [], 0).status).toBe('pending');
  expect(City.decision(person, g, { ...evidence, recognition: 'caseReview' }, [], 0).status).toBe('pending');
  expect(City.decision(person, g, { ...evidence, recognition: 'refused' }, [], 0).status).toBe('refused');
  const conditional = City.decision(person, gate('strained'), evidence, [], 0);
  expect(conditional.status).toBe('conditional'); expect(conditional.scope).toBe('visitorAnnexOnly');
  expect(City.canEnter(conditional, false)).toBe(false); expect(City.canEnter(conditional, true)).toBe(true);
});
test('fuel, pilot, money, reservations, expiry, and one-time refunds govern the actual round trip', () => {
  const s = City.create(), p = provider(), g = gate(), t = City.request(s, g.id, p.id, [person], 60, 0);
  p.aircraft.fuelKm = 150; expect(City.transportReason(p, 60, 0)).toContain('fuel'); p.aircraft.fuelKm = 1200;
  p.pilot.health = 0; expect(City.transportReason(p, 60, 0)).toContain('pilot'); p.pilot.health = 100;
  City.offer(t, g, p, 120); expect(City.accept(t, g, p, 0, 121)).toBe(false);
  expect(City.accept(t, g, p, 10000, t.offer.expiresAt)).toBe(false);
  expect(City.accept(t, g, p, 10000, 121)).toBe(true); expect(p.aircraft.reservedBy).toBe(t.id); expect(g.berthReservedBy).toBe(t.id);
  expect(City.refund(t)).toBe(540); expect(City.refund(t)).toBe(0);
  t.payment.refunded = false; t.departedAt = 122; expect(City.refund(t)).toBe(0);
  expect(City.request(s, g.id, p.id, [person], 60, 200)).toBeNull();
  expect(JSON.parse(JSON.stringify(s))).toEqual(s);
});
test('city scenes and gate staff remain independently identified across repeat journeys', () => {
  const a = gate(), b = City.gate({ ...a, cityId: 'b', z: 17, createdAt: 100 });
  expect(a.checkpointRoomId).not.toBe(b.checkpointRoomId); expect(a.doorId).not.toBe(b.doorId); expect(b.clerk.mapCell.z).toBe(17);
});
async function fixture(page, options = {}) {
  await setup(page, options.companion ? [{ name: 'Dara Fen' }] : []);
  expect(await page.evaluate(() => window.helixHeresyDebug.prepareCastawayAssistanceForTest())).toBe(true);
  expect(await page.evaluate(options => window.helixHeresyDebug.prepareCityApproachForTest(options), options)).toBe(true);
}
const snapshot = page => page.evaluate(() => window.helixHeresyDebug.cityApproachSnapshot());
const gateWork = (page, kind, data = {}) => page.evaluate(({ kind, data }) => window.helixHeresyDebug.queueGateWork(kind, data, { confirmed: true, deferRender: true }), { kind, data });
const configureGate = (page, options) => page.evaluate(options => window.helixHeresyDebug.configureGateEnforcementForTest(options), options);
const configureRelief = (page, options) => page.evaluate(options => window.helixHeresyDebug.configureBanishmentReliefForTest(options), options);
async function reliefWork(page, kind, data = {}) { expect(await gateWork(page, kind, data), kind).toBe(true); await advance(page, 180); }
const advance = (page, seconds) => page.evaluate(seconds => window.helixHeresyDebug.advanceCityApproachForTest(seconds), seconds);
async function work(page, kind, data = {}) {
  const queued = await page.evaluate(({ kind, data }) => window.helixHeresyDebug.queueCityApproachWork(kind, data, { confirmed: true, deferRender: true }), { kind, data });
  expect(queued, kind === 'enter' && !queued ? JSON.stringify(await page.evaluate(() => window.helixHeresyDebug.cityApproachEntryDiagnostic())) : kind).toBe(true);
  await advance(page, 180);
}
async function arrive(page, companionId = '') {
  expect(await page.evaluate(id => window.helixHeresyDebug.requestCityApproach('test-city-gate', id, { deferRender: true }), companionId)).toBe(true);
  await advance(page, 120); expect((await snapshot(page)).trips.at(-1).status).toBe('offered');
  expect(await page.evaluate(() => window.helixHeresyDebug.acceptCityApproach({ confirmed: true, deferRender: true }))).toBe(true);
  await advance(page, 300); expect((await snapshot(page)).trips.at(-1).status).toBe('boarding');
  await work(page, 'outboundBoard');
  let s = await snapshot(page); expect(s.roomId).toBe(Aid.CABIN); expect(s.trips.at(-1).status).toBe('outbound');
  await advance(page, s.trips.at(-1).offer.flightSeconds + 30);
  s = await snapshot(page); expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(s.trips.at(-1).status).toBe('checkpoint');
}
test('gate breach creates separate local custody through physical property intake and survives reload', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await fixture(page); await arrive(page); await work(page, 'inspect'); await advance(page, 180);
  await configureGate(page, { power: 10000 }); await configureRelief(page, { batteries: 1 }); await reliefWork(page, 'reliefBattery');
  const before = await snapshot(page);
  expect(await gateWork(page, 'cross')).toBe(false); await advance(page, 5);
  expect((await snapshot(page)).gates[0].enforcement.cases).toHaveLength(0);
  await configureGate(page, { open: true }); expect(await gateWork(page, 'cross')).toBe(true);
  await advance(page, 30); let s = await snapshot(page), e = s.gates[0].enforcement;
  expect(s.roomId).toBe(s.gates[0].annexRoomId); expect(e.cases).toHaveLength(1); expect(e.cases[0].status).toBe('referred'); expect(e.response).toBeNull();
  await advance(page, 500); s = await snapshot(page); e = s.gates[0].enforcement;
  expect(e.response.stage, JSON.stringify({ response: e.response, cell: s.cell, tasks: s.tasks })).toBe('jailed');
  expect(s.roomId).toBe(e.cellRoomId); expect(e.jail.stays[0].facility.cityId).toBe(s.gates[0].cityId);
  await page.evaluate(() => window.helixHeresyDebug.advanceCityApproachForTest(0, { render: true }));
  await expect(page.locator('[data-gate-enforcement="true"]')).toContainText('Temporary local jail');
  expect(e.jail.stays[0].transport.mode).toBe('foot'); expect(e.cases[0].judgment).toBeNull();
  for (const id of e.propertyIds) { const stack = s.stacks.find(x => x.id === id); expect(stack.roomId).toBe(e.officeRoomId); expect(stack.carriedBy).toBeFalsy(); }
  expect(s.cases).toEqual(before.cases); expect(s.banishments).toEqual(before.banishments);
  await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState());
  expect((await snapshot(page)).gates[0].enforcement).toEqual(e);
  await reliefWork(page, 'reliefPetition', { reliefKind: 'temporary' }); await advance(page, 2800);
  let petition = (await snapshot(page)).gates[0].relief.petitions.at(-1); expect(petition.status).toBe('offered');
  await reliefWork(page, 'reliefAccept', { petitionId: petition.id });
  s = await snapshot(page); expect(s.gates[0].relief.petitions.at(-1).status).toBe('active'); expect(s.gates[0].enforcement.response.stage).toBe('jailed');
  expect(await page.evaluate(() => window.helixHeresyDebug.queueCityApproachWork('enter', {}, { confirmed: true, deferRender: true }))).toBe(false);
  expect(await gateWork(page, 'water')).toBe(true); await advance(page, 100);
  expect((await snapshot(page)).stacks.find(x => x.id === e.waterId).quantity).toBe(11);
  expect(await gateWork(page, 'counsel')).toBe(true); await advance(page, 7300);
  s = await snapshot(page); const request = s.gates[0].enforcement.jail.stays[0].communications.requests[0]; expect(request.status).toBe('ready');
  expect(await gateWork(page, 'speakCounsel', { requestId: request.id })).toBe(true); await advance(page, 1900);
  s = await snapshot(page); expect(s.gates[0].enforcement.jail.stays[0].communications.requests[0].status, JSON.stringify(s.tasks)).toBe('completed');
  expect(await gateWork(page, 'review')).toBe(true); await advance(page, 1100);
  expect((await snapshot(page)).gates[0].enforcement.reviews.at(-1).result.kind).toBe('scopeConfirmed');
  await configureGate(page, { sourceActorId: 'corrected-other-person' }); const amended = (await snapshot(page)).cases;
  expect(await gateWork(page, 'review')).toBe(true); await advance(page, 1200);
  s = await snapshot(page); expect(s.gates[0].enforcement.response.stage).toBe('released'); expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(s.cases).toEqual(amended); expect(errors).toEqual([]);
});
test('receiving-city hearing uses disclosed local evidence, counsel, real escort and refundable bail', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await fixture(page); await arrive(page); await work(page, 'inspect'); await advance(page, 180);
  const before = await snapshot(page);
  await configureGate(page, { open: true }); expect(await gateWork(page, 'cross')).toBe(true); await advance(page, 530);
  let s = await snapshot(page); expect(s.gates[0].enforcement.response.stage).toBe('jailed');
  await configureGate(page, { prosecutorHealth: 0 }); await advance(page, 1200);
  s = await snapshot(page); expect(s.gates[0].enforcement.cases[0].pretrial.phase).toBe('screening');
  await configureGate(page, { prosecutorHealth: 100 }); await advance(page, 60);
  await reliefWork(page, 'courtDisclosure'); await reliefWork(page, 'courtCounsel', { counselKind: 'public' });
  expect(await gateWork(page, 'courtHearing')).toBe(false);
  expect(await gateWork(page, 'courtConference')).toBe(true); await advance(page, 1810);
  s = await snapshot(page); let e = s.gates[0].enforcement, court = e.cases[0].pretrial;
  expect(court.legal.proceedings[0].counsel.conferences).toHaveLength(1); expect(court.packet.notice.officerId).toBe('guard-aster');
  await configureGate(page, { guardHealth: 0 }); await reliefWork(page, 'courtHearing', { submission: 'securedBail', statement: 'notGuilty' });
  s = await snapshot(page); expect(s.roomId).toBe(e.cellRoomId); expect(s.gates[0].enforcement.cases[0].pretrial.phase).toBe('escortPending');
  await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState());
  await configureGate(page, { guardHealth: 100, blockHearingPath: true }); await advance(page, 60);
  s = await snapshot(page); expect(s.roomId).toBe(e.cellRoomId); expect(s.gates[0].enforcement.cases[0].pretrial.phase).toBe('escortPending');
  await configureGate(page, { blockHearingPath: false }); await advance(page, 60);
  s = await snapshot(page); e = s.gates[0].enforcement; expect(s.roomId).toBe(e.hearingRoomId); expect(e.response.stage).toBe('hearing'); expect(e.reviewer.mapCell).toEqual({ x: 28, y: 14, z: s.cell.z });
  await configureGate(page, { reviewerHealth: 0 }); await advance(page, 1000); expect((await snapshot(page)).gates[0].enforcement.cases[0].pretrial.phase).toBe('hearing');
  await configureGate(page, { reviewerHealth: 100 }); await advance(page, 100);
  s = await snapshot(page); e = s.gates[0].enforcement; court = e.cases[0].pretrial;
  expect(e.response.stage).toBe('jailed'); expect(court.phase).toBe('bailPending'); expect(court.handoff.statement).toBe('notGuilty'); expect(court.handoff.trialAt).toBeNull();
  const balance = s.money; await reliefWork(page, 'courtBail'); await advance(page, 60);
  s = await snapshot(page); e = s.gates[0].enforcement; expect(s.money).toBe(balance - 50); expect(e.response.stage).toBe('released'); expect(s.roomId).toBe(s.gates[0].checkpointRoomId);
  expect(e.cases[0].pretrial.phase).toBe('handedOff'); expect(e.cases[0].pretrial.legal.proceedings[0].release.escrowStatus).toBe('held'); expect(await gateWork(page, 'courtBail')).toBe(false);
  expect(s.cases).toEqual(before.cases); expect(s.banishments).toEqual(before.banishments); expect(e.cases[0].judgment).toBeNull();
  await page.evaluate(() => window.helixHeresyDebug.advanceCityApproachForTest(0, { render: true }));
  await expect(page.locator('[data-city-pretrial="true"]')).toContainText('separate receiving-city trial');
  const saved = e.cases[0].pretrial; await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState()); expect((await snapshot(page)).gates[0].enforcement.cases[0].pretrial).toEqual(saved);
  expect(errors).toEqual([]);
});
test('receiving-city dismissal clears pending relief without granting admission or reopening punishment', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await fixture(page); await arrive(page); await work(page, 'inspect'); await advance(page, 180);
  await configureRelief(page, { batteries: 1 }); await configureGate(page, { power: 10000 }); await reliefWork(page, 'reliefBattery');
  await configureGate(page, { open: true }); expect(await gateWork(page, 'cross')).toBe(true); await advance(page, 530);
  await configureGate(page, { sourceActorId: 'other-person' }); await advance(page, 1200);
  let s = await snapshot(page), e = s.gates[0].enforcement;
  expect(e.cases[0].status).toBe('chargesDismissed'); expect(e.response.stage).toBe('released'); expect(s.roomId).toBe(s.gates[0].checkpointRoomId);
  expect(e.cases[0].pretrial.legal.proceedings[0].release.kind).toBe('dismissal'); expect(s.banishments[0].status).toBe('active');
  await configureGate(page, { sourceActorId: 'scientist' }); await reliefWork(page, 'reliefSponsor');
  s = await snapshot(page); expect(s.gates[0].relief.sponsorship).toBeTruthy(); expect(e.cases[0].judgment).toBeNull(); expect(errors).toEqual([]);
});
async function localTrialFixture(page, options = {}) {
  await fixture(page, options); await arrive(page); await work(page, 'inspect'); await advance(page, 180);
  await configureGate(page, { open: true }); expect(await gateWork(page, 'cross')).toBe(true); await advance(page, 1530);
  await reliefWork(page, 'courtDisclosure'); await reliefWork(page, 'courtCounsel', { counselKind: 'self' });
  await reliefWork(page, 'courtHearing', { submission: 'securedBail', statement: 'notGuilty' }); await advance(page, 1000);
  await reliefWork(page, 'courtBail'); await advance(page, 60); await reliefWork(page, 'trialOpen');
}
test('receiving-city trial proves local elements in a physical hearing and settles bail separately from its fine', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message)); await localTrialFixture(page);
  const before = await snapshot(page);
  await reliefWork(page, 'trialChallenge', { challenge: 'observation' });
  await configureGate(page, { blockHearingPath: true }); expect(await gateWork(page, 'trialNotice')).toBe(false);
  await configureGate(page, { blockHearingPath: false }); await reliefWork(page, 'trialNotice');
  let s = await snapshot(page), t = s.gates[0].enforcement.cases[0].trial;
  expect(t.notice.servedById).toBe('clerk-aster'); expect(t.permit.generalAdmission).toBe(false); expect(await gateWork(page, 'trialAttend')).toBe(false);
  await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState()); await advance(page, t.notice.trialAt - (await snapshot(page)).clock);
  await reliefWork(page, 'trialAttend'); s = await snapshot(page); expect(s.roomId).toBe(s.gates[0].enforcement.hearingRoomId);
  await configureGate(page, { prosecutorHealth: 0 }); await advance(page, 700); expect((await snapshot(page)).gates[0].enforcement.cases[0].trial.phase).toBe('prosecution');
  await configureGate(page, { prosecutorHealth: 100 }); await advance(page, 700);
  s = await snapshot(page); expect(s.gates[0].enforcement.cases[0].trial.phase).toBe('defenseReady');
  await reliefWork(page, 'trialDefense'); await advance(page, 1500);
  s = await snapshot(page); t = s.gates[0].enforcement.cases[0].trial; expect(t.judgment.verdict).toBe('guilty'); expect(t.findings.map(f => f.id)).toEqual(['identity', 'obstructiveAct', 'lawfulProcess', 'knowledge']);
  const balance = s.money; await reliefWork(page, 'trialSentence', { submission: 'proportionateFine' }); await advance(page, 750);
  s = await snapshot(page); t = s.gates[0].enforcement.cases[0].trial;
  expect(t.phase).toBe('completed'); expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(s.gates[0].enforcement.response.stage).toBe('released');
  expect(s.money).toBe(balance + 50); expect(t.sentence.status).toBe('due'); expect(t.physicalRelease.mode).toBe('foot');
  expect(s.gates[0].enforcement.cases[0].status).toBe('resolved'); expect(s.cases).toEqual(before.cases); expect(s.banishments).toEqual(before.banishments);
  const fine = t.sentence.amount; await reliefWork(page, 'trialFine'); s = await snapshot(page); expect(s.money).toBe(balance + 50 - fine); expect(await gateWork(page, 'trialFine')).toBe(false);
  expect(await gateWork(page, 'executionOpen')).toBe(false);
  await page.evaluate(() => window.helixHeresyDebug.advanceCityApproachForTest(0, { render: true })); await expect(page.locator('[data-city-trial="true"]')).toContainText('guilty');
  const saved = s.gates[0].enforcement.cases[0]; await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState()); expect((await snapshot(page)).gates[0].enforcement.cases[0]).toEqual(saved);
  expect(errors).toEqual([]);
});
test('receiving-city trial adjourns when return transport fails and later dismisses unsupported attribution', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message)); await localTrialFixture(page);
  await reliefWork(page, 'trialNotice'); await work(page, 'returnBoard'); let s = await snapshot(page);
  await advance(page, s.trips.at(-1).offer.flightSeconds + 90); s = await snapshot(page); expect(s.roomId).toBe(Aid.PAD);
  await page.evaluate(() => window.helixHeresyDebug.configureCityApproachForTest({ condition: 0 }));
  const trialAt = s.gates[0].enforcement.cases[0].trial.notice.trialAt; await advance(page, Math.max(1, trialAt - s.clock + 60));
  s = await snapshot(page); let c = s.gates[0].enforcement.cases[0]; expect(c.trial.phase).toBe('adjourned'); expect(c.pretrial.legal.proceedings[0].release.escrowStatus).toBe('held'); expect(c.pretrial.legal.proceedings[0].fugitive.active).toBe(false); expect(c.judgment).toBeNull();
  await page.evaluate(() => window.helixHeresyDebug.configureCityApproachForTest({ condition: 100, readyAt: 0 })); await arrive(page);
  await configureGate(page, { sourceActorId: 'corrected-person' }); const balance = (await snapshot(page)).money;
  await reliefWork(page, 'trialWithdraw'); await advance(page, 60); s = await snapshot(page); c = s.gates[0].enforcement.cases[0];
  expect(c.trial.judgment.verdict).toBe('dismissed'); expect(c.status).toBe('resolved'); expect(s.money).toBe(balance + 50); expect(s.banishments[0].status).toBe('active'); expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(errors).toEqual([]);
});
test('receiving-city execution reserves exact assets and records reporting without custody or sentence service', async ({ page }) => {
  test.setTimeout(420000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await localTrialFixture(page, { trialSanctions: ['finitePrison'] }); await reliefWork(page, 'trialNotice');
  let s = await snapshot(page); await advance(page, s.gates[0].enforcement.cases[0].trial.notice.trialAt - s.clock);
  await reliefWork(page, 'trialAttend'); await advance(page, 700); await reliefWork(page, 'trialDefense'); await advance(page, 1500); await reliefWork(page, 'trialSentence'); await advance(page, 750);
  s = await snapshot(page); const before = structuredClone(s), beforeCase = s.gates[0].enforcement.cases[0]; expect(beforeCase.trial.phase).toBe('sentenceHandoff'); expect(s.roomId).toBe(s.gates[0].checkpointRoomId);
  await reliefWork(page, 'executionOpen'); await configureGate(page, { reviewerHealth: 0 }); await reliefWork(page, 'executionReview'); await advance(page, 1000);
  s = await snapshot(page); expect(s.gates[0].enforcement.cases[0].execution.phase).toBe('reviewing'); expect(s.gates[0].enforcement.cases[0].execution.progress).toBe(0);
  await configureGate(page, { reviewerHealth: 100 }); await advance(page, 1000);
  s = await snapshot(page); expect(s.gates[0].enforcement.cases[0].execution.phase).toBe('readyToPlan'); await reliefWork(page, 'executionReserve');
  s = await snapshot(page); let e = s.gates[0].enforcement, execution = e.cases[0].execution, resources = e.executionResources;
  expect(resources.vehicle.reservedBy).toBe(execution.plan.id); expect(resources.vehicle.fuelKm).toBe(40); expect(resources.vehicle.reservedFuelKm).toBe(8); expect(resources.crew.every(a => a.reservedBy === execution.plan.id)).toBe(true); expect(resources.facility.beds.filter(b => b.reservedBy === execution.plan.id)).toHaveLength(1);
  await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState()); expect((await snapshot(page)).gates[0].enforcement.executionResources).toEqual(resources);
  await reliefWork(page, 'executionNotice'); s = await snapshot(page); execution = s.gates[0].enforcement.cases[0].execution;
  expect(execution.notice.custodyAuthorized).toBe(false); expect(await gateWork(page, 'executionReport')).toBe(false); await advance(page, execution.notice.reportAt - s.clock); await reliefWork(page, 'executionReport');
  s = await snapshot(page); e = s.gates[0].enforcement; execution = e.cases[0].execution;
  expect(execution.phase).toBe('readyForPhysicalTransfer'); expect(execution.notice.witnessId).toBe('clerk-aster'); expect(execution.plan.departureAt).toBeNull(); expect(execution.plan.admissionAt).toBeNull(); expect(execution.ledger.prisonServedSeconds).toBe(0); expect(execution.ledger.creditAppliedAt).toBeNull(); expect(execution.custodyAuthority).toBeNull();
  expect(e.response.stage).toBe('released'); expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(s.money).toBe(before.money); expect(s.cases).toEqual(before.cases); expect(s.banishments).toEqual(before.banishments); expect(e.cases[0].trial).toEqual(beforeCase.trial);
  await page.evaluate(() => window.helixHeresyDebug.advanceCityApproachForTest(0, { render: true })); await expect(page.locator('[data-city-execution="true"]')).toContainText('Ready for the separate physical-transfer pass');
  const reportedAt = execution.notice.reportedAt; await page.evaluate(() => window.helixHeresyDebug.configureCityExecutionForTest({ vehicleCondition: 0 })); await advance(page, 60);
  s = await snapshot(page); e = s.gates[0].enforcement; execution = e.cases[0].execution; expect(execution.phase).toBe('postponed'); expect(execution.notices[0].reportedAt).toBe(reportedAt); expect(e.executionResources.vehicle.reservedBy).toBeNull(); expect(e.executionResources.vehicle.fuelKm).toBe(40); expect(e.executionResources.crew.every(a => !a.reservedBy)).toBe(true); expect(e.executionResources.facility.beds.every(b => !b.reservedBy)).toBe(true); expect(e.response.stage).toBe('released'); expect(e.cases[0].trial.sentence.executionStartedAt).toBeNull();
  const saved = execution; await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState()); expect((await snapshot(page)).gates[0].enforcement.cases[0].execution).toEqual(saved); expect(errors).toEqual([]);
});
test('discretionary relief consumes actual service evidence, preserves counteroffer consent and expires without arrest', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await fixture(page); await arrive(page); await work(page, 'inspect'); await advance(page, 180);
  const before = await snapshot(page);
  await reliefWork(page, 'reliefPetition', { reliefKind: 'temporary' }); await advance(page, 2800);
  expect((await snapshot(page)).gates[0].relief.petitions.at(-1).result.kind).toBe('refused');
  await reliefWork(page, 'reliefPetition', { reliefKind: 'temporary' }); expect((await snapshot(page)).gates[0].relief.petitions).toHaveLength(1);
  await configureRelief(page, { batteries: 1 }); expect(await gateWork(page, 'reliefBattery')).toBe(false);
  await configureGate(page, { power: 0 }); await reliefWork(page, 'reliefBattery'); await reliefWork(page, 'reliefSponsor');
  let s = await snapshot(page); expect(s.gates[0].relief.receipts).toHaveLength(1); expect(s.stacks.some(x => x.key === 'relayBattery' && x.carriedBy === 'scientist' && x.quantity > 0)).toBe(false);
  expect(s.gates[0].powerSeconds).toBeGreaterThan(13000);
  await reliefWork(page, 'reliefPetition', { reliefKind: 'permanent' });
  await configureGate(page, { power: 0 }); await advance(page, 1200); expect((await snapshot(page)).gates[0].relief.petitions.at(-1).status).toBe('verifying');
  await configureGate(page, { power: 40000 }); await advance(page, 1900);
  s = await snapshot(page); let p = s.gates[0].relief.petitions.at(-1); expect(p.result.kind).toBe('counteroffer'); expect(p.grant).toBeNull();
  expect(await page.evaluate(() => window.helixHeresyDebug.queueCityApproachWork('enter', {}, { confirmed: true, deferRender: true }))).toBe(false);
  await reliefWork(page, 'reliefAccept', { petitionId: p.id }); s = await snapshot(page); p = s.gates[0].relief.petitions.at(-1);
  expect(s.trips.at(-1).decisions[0].status).toBe('conditional'); expect(p.grant.kind).toBe('temporary');
  await work(page, 'enter'); expect((await snapshot(page)).roomId).toBe(s.gates[0].annexRoomId);
  await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState());
  expect((await snapshot(page)).gates[0].relief.petitions.at(-1).grant).toEqual(p.grant);
  await advance(page, p.grant.expiresAt - 900 - (await snapshot(page)).clock);
  s = await snapshot(page); expect(s.gates[0].relief.petitions.at(-1).warnedAt).toBeTruthy(); expect(s.trips.at(-1).acceptedConditions).toBe(true);
  await advance(page, 900); s = await snapshot(page); expect(s.gates[0].relief.petitions.at(-1).status).toBe('expired');
  expect(s.roomId).toBe(s.gates[0].annexRoomId); expect(s.gates[0].enforcement.cases).toHaveLength(0); expect(s.trips.at(-1).decisions[0].status).toBe('refused');
  await page.evaluate(() => window.helixHeresyDebug.advanceCityApproachForTest(0, { render: true }));
  await expect(page.locator('[data-banishment-relief]')).toContainText('Permission expired');
  expect(await page.evaluate(g => window.helixHeresyDebug.startScientistMove(g.checkpointRoomId, { toCell: { x: 10, y: 7, z: g.z }, allowMultiRoom: true }), s.gates[0])).toBeTruthy();
  await advance(page, 60); s = await snapshot(page); expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(s.cases).toEqual(before.cases); expect(s.banishments).toEqual(before.banishments); expect(s.money).toBe(before.money); expect(errors).toEqual([]);
  await configureRelief(page, { agedCalendar: true, batteries: 1 }); await configureGate(page, { power: 0 });
  await reliefWork(page, 'reliefBattery'); await reliefWork(page, 'reliefSponsor');
  await reliefWork(page, 'reliefPetition', { reliefKind: 'permanent' }); await advance(page, 2800);
  p = (await snapshot(page)).gates[0].relief.petitions.at(-1); expect(p.result.reliefKind).toBe('permanent');
  await reliefWork(page, 'reliefAccept', { petitionId: p.id }); s = await snapshot(page);
  expect(s.gates[0].relief.petitions.at(-1).grant.expiresAt).toBeNull(); expect(s.trips.at(-1).decisions[0].status).toBe('admitted');
  expect(s.cases).toEqual(before.cases); expect(s.banishments).toEqual(before.banishments); expect(s.gates[0].enforcement.cases).toHaveLength(0);
  await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState());
  await work(page, 'inspect'); await advance(page, 180); expect((await snapshot(page)).trips.at(-1).decisions[0].status).toBe('admitted'); expect(errors).toEqual([]);
});
test('cancelled or unseen gate crossing produces no allegation and lifted bans are reviewed without pardon', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await fixture(page); await arrive(page); await work(page, 'inspect'); await advance(page, 180);
  await configureGate(page, { open: true }); expect(await gateWork(page, 'cross')).toBe(true);
  await configureGate(page, { cancelCross: true }); await advance(page, 10);
  let s = await snapshot(page); expect(s.gates[0].enforcement.intent).toBeNull(); expect(s.gates[0].enforcement.cases).toHaveLength(0);
  await configureGate(page, { guardHealth: 0 }); expect(await gateWork(page, 'cross')).toBe(true); await advance(page, 30);
  s = await snapshot(page); expect(s.roomId).toBe(s.gates[0].annexRoomId); expect(s.gates[0].enforcement.cases).toHaveLength(0);
  await configureGate(page, { guardHealth: 100, banStatus: 'lifted' });
  expect(await gateWork(page, 'review')).toBe(true); await advance(page, 1100);
  s = await snapshot(page); expect(s.gates[0].enforcement.reviews.at(-1).result.kind).toBe('corrected'); expect(s.trips.at(-1).decisions[0].status).toBe('admitted'); expect(errors).toEqual([]);
});
test('physical local refusal preserves separate passenger admission and paid return without arrest', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await fixture(page, { companion: true, companionRelief: true }); let before = await snapshot(page); const companion = before.actors[0].id;
  expect(await page.evaluate(id => window.helixHeresyDebug.requestCityApproach('test-city-gate', id, { deferRender: true }), companion)).toBe(false);
  await work(page, 'invite', { personId: companion, gateId: 'test-city-gate' });
  await arrive(page, companion);
  expect(await page.evaluate(() => window.helixHeresyDebug.queueCityApproachWork('enter', {}, { confirmed: true, deferRender: true }))).toBe(false);
  await work(page, 'inspect'); await advance(page, 180); let s = await snapshot(page);
  expect(s.trips.at(-1).decisions.map(d => d.status)).toEqual(['refused', 'admitted']);
  expect(s.banishments).toEqual(before.banishments); expect(s.cases).toEqual(before.cases);
  expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(s.provider.aircraft.fuelKm).toBe(1140);
  await work(page, 'companionEnter', { personId: companion }); s = await snapshot(page);
  expect(s.actors[0].roomId).toBe(s.gates[0].annexRoomId); expect(s.trips.at(-1).enteredIds).toEqual([companion]);
  await page.evaluate(() => window.helixHeresyDebug.reloadSurveyExpeditionTestState());
  await work(page, 'returnBoard'); s = await snapshot(page); expect(s.roomId).toBe(Aid.CABIN);
  await advance(page, s.trips.at(-1).offer.flightSeconds + 30); s = await snapshot(page);
  expect(s.roomId).toBe(Aid.PAD); expect(s.trips.at(-1).status).toBe('returned'); expect(s.provider.aircraft.fuelKm).toBe(1080);
  expect(s.trips.at(-1).returningIds).toEqual(['scientist']); expect(s.actors[0].roomId).toBe(s.gates[0].annexRoomId); expect(s.money).toBe(before.money - 540);
  expect(s.health).toBe(before.health); expect(s.stacks.map(x => x.id).sort()).toEqual(before.stacks.map(x => x.id).sort());
  expect(s.cases).toEqual(before.cases); expect(errors).toEqual([]);
});
test('foreign conditional refuge requires physical inspection and accepted scope; releasing aircraft is explicit', async ({ page }) => {
  test.setTimeout(360000); const errors = []; page.on('pageerror', e => errors.push(e.message));
  await fixture(page, { foreign: true, conditional: true }); const before = await snapshot(page);
  expect(await page.evaluate(() => window.helixHeresyDebug.requestCityApproach('test-city-gate', '', { deferRender: true }))).toBe(true);
  await advance(page, 120); expect(await page.evaluate(() => window.helixHeresyDebug.acceptCityApproach({ confirmed: true, deferRender: true }))).toBe(true);
  await page.evaluate(() => window.helixHeresyDebug.configureCityApproachForTest({ condition: 20 })); await advance(page, 300);
  expect((await snapshot(page)).money).toBe(before.money);
  await page.evaluate(() => window.helixHeresyDebug.configureCityApproachForTest({ condition: 100 }));
  await arrive(page);
  await page.evaluate(() => window.helixHeresyDebug.configureCityApproachForTest({ recognition: 'caseReview' }));
  await work(page, 'inspect'); await advance(page, 180); expect((await snapshot(page)).trips.at(-1).decisions[0].status).toBe('pending');
  await page.evaluate(() => window.helixHeresyDebug.configureCityApproachForTest({ recognition: 'verified' }));
  await work(page, 'inspect'); await advance(page, 180);
  let s = await snapshot(page); expect(s.trips.at(-1).decisions[0].status).toBe('conditional');
  expect(s.roomId).toBe(s.gates[0].checkpointRoomId); expect(s.banishments).toEqual(before.banishments);
  await work(page, 'enter'); s = await snapshot(page); expect(s.roomId).toBe(s.gates[0].annexRoomId); expect(s.trips.at(-1).enteredIds).toEqual(['scientist']);
  expect(s.provider.pilot.location).toBe('cityCheckpoint');
  await page.evaluate(() => window.helixHeresyDebug.advanceCityApproachForTest(0, { render: true }));
  await page.locator('[data-workspace-tab="visits"]').click(); await expect(page.locator('[data-city-approach]')).toContainText('conditional');
  expect(await page.evaluate(() => window.helixHeresyDebug.releaseCityAircraft({ confirmed: true, deferRender: true }))).toBe(true);
  await advance(page, s.trips.at(-1).offer.flightSeconds);
  s = await snapshot(page); expect(s.trips.at(-1).status).toBe('settled'); expect(s.roomId).toBe(s.gates[0].annexRoomId);
  expect(s.provider.pilot.location).toBe('receivingPad'); expect(s.provider.aircraft.fuelKm).toBe(1080);
  expect(s.cases).toEqual(before.cases); expect(errors).toEqual([]);
});
